import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Hoc/Provider'
import ResponsiveNav from '@/components/Home/NavBar/ResponsiveNav'
import Footer from '@/components/Home/Footer/Footer'
import ScrollToTop from '@/components/Helper/ScrollToTop'

const font = Inter({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],
})

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Tee Portfolio",
  description: "Generated by Next.js 16.3",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" className='scroll-smooth' suppressHydrationWarning>
      <body className={`${font.className} h-full antialiased`}>
        <Provider>
          <ResponsiveNav />
          {children}
          <Footer />
          <ScrollToTop/>
          </Provider>
        </body>
    </html>
  )
}
